# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amine/workspace/yasimSBML

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amine/workspace/yasimSBML

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amine/workspace/yasimSBML/CMakeFiles /home/amine/workspace/yasimSBML/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amine/workspace/yasimSBML/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yasimSBML.exe

# Build rule for target.
yasimSBML.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yasimSBML.exe
.PHONY : yasimSBML.exe

# fast build rule for target.
yasimSBML.exe/fast:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/build
.PHONY : yasimSBML.exe/fast

# Manual pre-install relink rule for target.
yasimSBML.exe/preinstall:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/preinstall
.PHONY : yasimSBML.exe/preinstall

#=============================================================================
# Target rules for targets named html

# Build rule for target.
html: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 html
.PHONY : html

# fast build rule for target.
html/fast:
	$(MAKE) -f doc/CMakeFiles/html.dir/build.make doc/CMakeFiles/html.dir/build
.PHONY : html/fast

src/especes.o: src/especes.c.o
.PHONY : src/especes.o

# target to build an object file
src/especes.c.o:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/especes.c.o
.PHONY : src/especes.c.o

src/especes.i: src/especes.c.i
.PHONY : src/especes.i

# target to preprocess a source file
src/especes.c.i:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/especes.c.i
.PHONY : src/especes.c.i

src/especes.s: src/especes.c.s
.PHONY : src/especes.s

# target to generate assembly for a file
src/especes.c.s:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/especes.c.s
.PHONY : src/especes.c.s

src/simulation.o: src/simulation.c.o
.PHONY : src/simulation.o

# target to build an object file
src/simulation.c.o:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/simulation.c.o
.PHONY : src/simulation.c.o

src/simulation.i: src/simulation.c.i
.PHONY : src/simulation.i

# target to preprocess a source file
src/simulation.c.i:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/simulation.c.i
.PHONY : src/simulation.c.i

src/simulation.s: src/simulation.c.s
.PHONY : src/simulation.s

# target to generate assembly for a file
src/simulation.c.s:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/simulation.c.s
.PHONY : src/simulation.c.s

src/yasimSBML.o: src/yasimSBML.c.o
.PHONY : src/yasimSBML.o

# target to build an object file
src/yasimSBML.c.o:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/yasimSBML.c.o
.PHONY : src/yasimSBML.c.o

src/yasimSBML.i: src/yasimSBML.c.i
.PHONY : src/yasimSBML.i

# target to preprocess a source file
src/yasimSBML.c.i:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/yasimSBML.c.i
.PHONY : src/yasimSBML.c.i

src/yasimSBML.s: src/yasimSBML.c.s
.PHONY : src/yasimSBML.s

# target to generate assembly for a file
src/yasimSBML.c.s:
	$(MAKE) -f CMakeFiles/yasimSBML.exe.dir/build.make CMakeFiles/yasimSBML.exe.dir/src/yasimSBML.c.s
.PHONY : src/yasimSBML.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... yasimSBML.exe"
	@echo "... html"
	@echo "... src/especes.o"
	@echo "... src/especes.i"
	@echo "... src/especes.s"
	@echo "... src/simulation.o"
	@echo "... src/simulation.i"
	@echo "... src/simulation.s"
	@echo "... src/yasimSBML.o"
	@echo "... src/yasimSBML.i"
	@echo "... src/yasimSBML.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

